website/auth.py
from flask import Blueprint, render_template, request, flash, redirect, url_for
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import login_user, login_required, logout_user, current_user
from firebase_admin import firestore

from website.models import User

# Initialize Firestore client
db = firestore.client()

auth = Blueprint('auth', __name__)

@auth.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        email = request.form.get('email')
        password = request.form.get('password')

        user_ref = db.collection('users').document(email).get()
        if user_ref.exists:
            user_data = user_ref.to_dict()
            if check_password_hash(user_data['password'], password):
                flash('Welcome to Easy Link!', category='success')
                user = User(email=user_data['email'], firstname=user_data['firstname'], lastname=user_data['lastname'], password=user_data['password'])  # Create a User object
                login_user(user, remember=True)
                return redirect(url_for('views.home'))
            else:
                flash('Incorrect password, try again.', category='error')
        else:
            flash('Email does not exist.', category='error')

    return render_template("login.html", user=current_user)

@auth.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('auth.login'))

@auth.route('/sign-up', methods=['GET', 'POST'])
def sign_up():
    if request.method == 'POST':
        email = request.form.get('email')
        lastname = request.form.get('lastname')
        firstname = request.form.get('firstname')
        password1 = request.form.get('password1')
        password2 = request.form.get('password2')

        if not all([email, lastname, firstname, password1, password2]):
            flash('All fields are required!', category='error')
            return redirect(url_for('auth.sign_up'))

        user_ref = db.collection('users').document(email).get()
        if user_ref.exists:
            flash('Email address already in use. Please use a different email.', category='error')
            return redirect(url_for('auth.sign_up'))

        if password1 != password2:
            flash('Passwords do not match!', category='error')
            return redirect(url_for('auth.sign_up'))

        # Create a new user in Firestore
        new_user = {
            'email': email,
            'firstname': firstname,
            'lastname': lastname,
            'password': generate_password_hash(password1, method='pbkdf2:sha256')  # Hash the password
        }
        db.collection('users').document(email).set(new_user)  # Store the user document in Firestore

        flash('Account created!', category='success')
        login_user(User(email=email, firstname=firstname, lastname=lastname, password=new_user['password']), remember=True)  # Create User object
        return redirect(url_for('auth.login'))

    return render_template("sign-up.html", user=current_user)

website/views.py
import requests
from bs4 import BeautifulSoup
import os
from flask import Blueprint, app, current_app, flash, jsonify, redirect, render_template, request, session, url_for, abort
from flask_login import  current_user, login_required
from werkzeug.utils import secure_filename
from .models import DataPosts, MemoPosts, NetworkPosts, QuestionPosts, User, UserProfile, tradepost, Posts, CyberPosts, Save
from website import db
from firebase_admin import firestore

db = firestore.client()


views = Blueprint('views', __name__)


def allowed_file(filename):
    return '.' in filename and filename.rsplit('.', 1)[1].lower() in current_app.config['ALLOWED_EXTENSIONS']

@views.route('/', methods=['GET', 'POST'])

def home(): 
    name="Ayanda!"
    return render_template("home.html", Hello='Welcome to Lecture.AI ' + name )

@views.route('/nexus')
def nexus():
    return render_template("nexus.html")

@views.route('/profile')
@login_required
def profile():
     # Retrieve the user's data from the database using their session ID/email/username
    user = current_user
    # Render the profile template and pass the user object
    return render_template("profile.html", user=user)


@views.route('/set_theme', methods=['POST'])
def set_theme():
    data = request.get_json()
    session['theme'] = data['theme']
    return '', 204  # No content response

@views.route('/sectorC')
def sectorC():
    return render_template("sectorC.html")

@views.route('/sectorD')
def sectorD():
    return render_template("sectorD.html")

@views.route('/sectorE')
def sectorE():
    return render_template("sectorE.html")

@views.route('/sectorF')
def sectorF():
    return render_template("sectorF.html")

@views.route('/sectorG')
def sectorG():
    return render_template("sectorG.html")

@views.route('/r-trade')
def trade():
    trades = tradepost.query.all()  # Fetch all trades
    for trade in trades:
        print(f"Trade image: {trade.image}") 
    return render_template('r-trade.html', trades=trades)

@views.route('/create-trade', methods=['POST'])
@login_required
def create_trade():
    if request.method == 'POST':
        if not current_user.is_authenticated:  # Ensure the user is authenticated
            flash('You need to be logged in to create a trade!', category='error')
            return redirect(url_for('views.login'))
        
        image = request.files.get('image')
        description = request.form.get('caption')
      
        price = request.form.get('price')
        category = request.form.get('category')
 

        title = request.form.get('title')

        if image and allowed_file(image.filename):
            filename = secure_filename(image.filename)
            image.save(os.path.join(current_app.config['UPLOAD_FOLDER'], filename))

            new_trade = tradepost(
                image=filename,
                description=description,
                title=title, 
                price=float(price) if type == 'Sell' else None,
                category=category,
                
                user_id=current_user.id  # Only access id if current_user is authenticated
            )

            db.session.add(new_trade)
            db.session.commit()
            flash('Trade post created successfully!', category='success')
            return redirect(url_for('views.trade'))

    return redirect(url_for('views.trade'))



@views.route('/blog')
def blog():
    urls = [
        "https://www.bbc.com/future/article/20230317-how-recycling-can-help-the-climate-and-other-facts",
        "https://www.who.int/news-room/fact-sheets/detail/electronic-waste-%28e-waste%29",
        "https://freelancian.co.za/what-can-i-recycle-to-make-money-in-south-africa/"  
    ]

    articles = []

    for url in urls:
        try:
            response = requests.get(url)
            response.raise_for_status()  

         
            soup = BeautifulSoup(response.text, 'html.parser')

            article_content = soup.find('article')  

            articles.append({
                'title': soup.title.string if soup.title else 'No Title',
                'html': str(article_content)
            })

        except requests.RequestException as e:
            print(f"Error fetching article from {url}: {e}")
            articles.append({
                'title': 'Error Loading Article',
                'html': "<p>Error loading article</p>"
            })

    return render_template('blog.html', articles=articles)


@views.route('/videos')
def videos():
    video_list = [
        {'title': 'Artificial Intelligence Integrated in Recycling!', 'url': 'https://www.youtube.com/embed/On5WUCUNmfc'}, 
        {'title': 'Make Money Through Waste!', 'url': 'https://www.youtube.com/embed/cQqhKzcHnAg'},  
        {'title': 'AI Making Our Lives Easier!', 'url': 'https://www.youtube.com/embed/KPVSTjfcdng'}
    ]

    return render_template("videos.html", videos=video_list)



@views.route('/about')
def about():
    return render_template("about.html")

@views.route('/certificate')
def certificate():
    url = "https://environmentgo.com/free-online-recycling-courses/#:~:text=Free%20Online%20Recycling%20Courses%201%201.%20Advanced%20Diploma,Electronics%20for%20Recycling%20in%20a%20Circular%20Economy%20"

    try:
        response = requests.get(url)
        response.raise_for_status()  

        
        soup = BeautifulSoup(response.text, 'html.parser')

      
        content = soup.find('main')  

     
        content_html = str(content)

    except requests.RequestException as e:
        print(f"Error fetching certificate data: {e}")
        content_html = "<p>Error loading content</p>"

    return render_template('certificate.html', content_html=content_html)


@views.route('/help')
def help():
    return render_template("help.html")

@views.route('/privacy')
def privacy():
    return render_template("privacy.html")

@views.route('/terms')
def terms():
    return render_template("terms.html")



@views.route('/login')
def login():
    return render_template("login.html")



@views.route('/sign-up')
def sign_up():
    return render_template("sign-up.html")

@views.route('/create-profile', methods=['GET', 'POST'])
@login_required
def createProfile():
    
    
    if request.method == 'POST':
        firstname = request.form.get('firstName')
        lastname = request.form.get('lastName')
        bio = request.form.get('bio')
        location = request.form.get('location')
        workplace = request.form.get('workplace')
        education = request.form.get('education')
        highlights = request.form.get('highlights')
        linkedin = request.form.get('linkedin')
        facebook = request.form.get('facebook')
        instagram = request.form.get('instagram')
        media_type = request.form.get('mediaType')
        category_prefix = request.form.get('categoryPrefix')


        cover_photo = request.files.get('coverPhoto')
        media_uploads = request.files.getlist('mediaUpload')
        
        cover_photo_filename = None
        media_upload_filenames = []
        
        if cover_photo and allowed_file(cover_photo.filename):
            cover_photo_filename = secure_filename(cover_photo.filename)
            cover_photo.save(os.path.join(current_app.config['UPLOAD_FOLDER'], cover_photo_filename))
        
        for media_upload in media_uploads:
         if media_upload and allowed_file(media_upload.filename):
            filename = secure_filename(media_upload.filename)
            media_upload.save(os.path.join(current_app.config['UPLOAD_FOLDER'], filename))
            media_upload_filenames.append(filename)
            
        
        profile = UserProfile(
            firstname=firstname,
            lastname=lastname,
            bio=bio,
            location=location,
            workplace=workplace,
            education=education,
            highlights=highlights,
            linkedin=linkedin,
            facebook=facebook,
            instagram=instagram,
            cover_photo=cover_photo_filename,
            media_upload=','.join(media_upload_filenames),
            media_type='image' if media_uploads and media_uploads[0].content_type.startswith('image') else 'video', 
            user_id=current_user.id
        )

        db.session.add(profile)
        db.session.commit()
        flash('Profile created successfully!', category='success')
        return redirect(url_for('views.cans'))

    return render_template('create-profile.html')


@views.route('/cans')
def cans():
    profiles = UserProfile.query.all()
    return render_template("cans.html", profiles=profiles)

@views.route('/update-profile/<int:profile_id>', methods=['GET', 'POST'])
@login_required
def update(profile_id):
    profile = UserProfile.query.get_or_404(profile_id)

    if request.method == 'POST':
        profile.firstname = request.form.get('firstName')
        profile.lastname = request.form.get('lastName')
        profile.bio = request.form.get('bio')
        profile.location = request.form.get('location')
        profile.workplace = request.form.get('workplace')
        profile.education = request.form.get('education')
        profile.highlights = request.form.get('highlights')
        profile.linkedin = request.form.get('linkedin')
        profile.facebook = request.form.get('facebook')
        profile.instagram = request.form.get('instagram')

        # Handle cover photo upload
        cover_photo = request.files.get('coverPhoto')
        if cover_photo and allowed_file(cover_photo.filename):
            cover_photo_filename = secure_filename(cover_photo.filename)
            cover_photo.save(os.path.join(current_app.config['UPLOAD_FOLDER'], cover_photo_filename))
            profile.cover_photo = cover_photo_filename

        # Handle media uploads
        media_uploads = request.files.getlist('mediaUpload')
        media_filenames = []

        for media in media_uploads:
            if media and allowed_file(media.filename):

website/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
   

    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
      integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
      crossorigin="anonymous"
    />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
      crossorigin="anonymous"
    />
    <link
    rel="stylesheet"
    href="{{ url_for('static', filename='css/profile.css') }}"
    />
   
    <link
    rel="stylesheet"
    href="{{ url_for('static', filename='css/styles.css') }}"
  />
 
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">

    
    <title>{% block title %}Home{% endblock %}</title>
  </head>
  <body class="{% if session.theme %}{{ session.theme }}-theme{% endif %}">

  
    <!-- Popup Modal -->
    
    <div class="popup" id="factPopup">
      <div class="popup-content">
          <span class="close">&times;</span>
          <img id="factImage" src="" alt="Fact Image">
          <div id="factDescription"></div>
          <button id="okButton">OK</button>
      </div>
  </div>
  
 
    <nav class="navbar navbar-expand-lg navbar-teal-blue">
      <button
        class="navbar-toggler"
        type="button"
        data-toggle="collapse"
        data-target="#navbar"
        title="Toggle Navigation" 
      >

      
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbar">
        <div class="navbar-nav">
          <div class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="homeDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Easy Link
            </a>
            <div class="dropdown-menu" aria-labelledby="homeDropdown">
              <a class="dropdown-item" href="/">Home</a>
              <a class="dropdown-item" href="/profile">Profile</a>
              <a class="dropdown-item" href="/help">Help</a>
            </div>
          </div>
          <span class="search-icon" id="searchToggle" title="Search">&#128269;</span>
          
         
          {% if user.is_authenticated %}
          
          
          {% else %}
          {% endif %}
        </div>
        <div class="navbar-nav">
        </div>
          <div class="navbar-nav ml-auto">
            {% if user.is_authenticated %}
            <a class="nav-item nav-link" id="home-main" href="/">Home</a>
           
            
            <div class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="profileDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                MySchool
              </a>
              <div class="dropdown-menu" aria-labelledby="profileDropdown">
                <a class="dropdown-item" href="/sectorA">Sector A</a>
                <a class="dropdown-item" href="/sectorB">Sector B</a>
                <a class="dropdown-item" href="/sectorC">Sector C</a>
                <a class="dropdown-item" href="/sectorD">Sector D</a>
                <a class="dropdown-item" href="/sectorE">Sector E</a>
                <a class="dropdown-item" href="/sectorF">Sector F</a>
                <a class="dropdown-item" href="/sectorG">Sector G</a>
              </div>
            </div>
            <a class="nav-item nav-link" id="nex" href="/nex">Nexus</a>

            <div class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="profileDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Exams
              </a>
              <div class="dropdown-menu" aria-labelledby="profileDropdown">
                <a class="dropdown-item" href="/questions">Question Papers</a>
                <a class="dropdown-item" href="/memo">Memo</a>
              </div>
            </div>

            <div class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="profileDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Podcast
              </a>
              <div class="dropdown-menu" aria-labelledby="profileDropdown">
                <a class="dropdown-item" href="/engineer">Software Engineering</a>
                <a class="dropdown-item" href="/robotics">Robotics & Coding</a>
                <a class="dropdown-item" href="/physics">Physical Sciences</a>
                <a class="dropdown-item" href="/iot">Internet of Things</a>
                <a class="dropdown-item" href="/math">Mathematics</a>
                <a class="dropdown-item" href="/accounting">Accounting</a>
              </div>
            </div>

            
             
             
            <div class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="computersDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  Reels
              </a>
              <div class="dropdown-menu" aria-labelledby="computersDropdown">
                <a class="dropdown-item" href="/entrepreneurship">Entrepreneurship</a>
                <a class="dropdown-item" href="/agric">Agriculture</a>
                <a class="dropdown-item" href="/networks">Networks</a>
                <a class="dropdown-item" href="/numbers">Numbers</a>
                <a class="dropdown-item" href="/science">Science</a>
                <a class="dropdown-item" href="/code">Code</a>
                <a class="dropdown-item" href="/ict">ICT</a>
                <a class="dropdown-item" href="/iot">IoT</a>
              </div>
          </div>
          
          <a class="nav-item nav-link" id="kca" href="/kca">K.C.A</a>
            
            <a class="nav-item nav-link" id="about" href="/about">About Us</a>
            
            <div class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" id="logout" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false" aria-label="Pick Profile">
                <i class="fa fa-sign-out" aria-hidden="true"></i>
              </a>
              <ul class="dropdown-menu" aria-labelledby="logout">
                <li>
                  <a class="dropdown-item" href="{{ url_for('auth.logout') }}" aria-label="Individual Profile">
                    <i class="fa fa-user" aria-hidden="true"></i> <!-- Individual icon -->
                  </a>
                </li>
                <li>
                  <a class="dropdown-item" href="{{ url_for('admin_auth.adm_logout') }}" aria-label="Admin Profile">
                    <i class="fa fa-user-shield" aria-hidden="true"></i> <!-- Admin icon -->
                  </a>
                </li>
              </ul>
            </div>
            
            
            

          {% else %}
          <a class="nav-item nav-link" id="home" href="/">Home</a>
          <a class="nav-item nav-link" id="signUp" href="/sign-up">Sign Up</a>
          <a class="nav-item nav-link" id="login" href="/login">Login</a>
          {% endif %}
        </div>
      </div>
    </nav>

    {% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
     {% for category, message in messages %}
     {% if category == 'error' %}
     <div class="alert alert-danger alter-dismissable fade show" role="alert">
      {{ message }}
      <button type="button" class="close" data-dismiss="alert"  aria-label="Close" title="Close alert">
        <span aria-hidden="true">&times;</span>
      </button>
     </div>

     {% else %}

     <div class="alert alert-success alter-dismissable fade show" role="alert">
      {{ message }}
      <button type="button" class="close" data-dismiss="alert"  aria-label="Close" title="Close alert">
        <span aria-hidden="true">&times;</span>
      </button>
     </div>
     {% endif %}
     {% endfor %}
    {% endif %} 
    {% endwith %}

    <div class="container content">
      {% block content %}
       {% endblock %}
    </div>

    <footer class="footer-teal-blue">
      <div class="container">
        <div class="row">
          <div class="col-md-6">
            <p>&copy; 2024 Easy Link. All rights reserved.</p>
          </div>
          <div class="col-md-6 text-md-right footer-links">
            <a href="/privacy">Privacy Policy</a>
            <a href="/terms">Terms of Service</a>
            <a href="/about">About Us</a>
          </div>
        </div>
      </div>
    </footer>
    


    <script
      src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
      integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
      integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
      integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
      crossorigin="anonymous"
    ></script>
    
    <script>
      const facts = [
    {
        image: 'static/images/old.jpg',
        description: 'Fact: Jeanne Calment lived to 122, the longest known human lifespan.'
    },
    {
        image: 'static/images/le.jpg',
        description: 'Fact: The human brain generates about 20 watts of power while awake.'
    },
    {
        image: 'static/images/left.jpg',
        description: 'Fact: About 90% of people are right-handed; lefties often excel in arts.'
    }
];

function openPopup() {
    const randomIndex = Math.floor(Math.random() * facts.length);
    const fact = facts[randomIndex];

    document.getElementById('factImage').src = fact.image;
    document.getElementById('factDescription').innerText = fact.description;

    document.getElementById('factPopup').style.display = 'block';
}

function shouldShowPopup() {
    const lastShown = localStorage.getItem('lastPopupTime');
    const currentTime = new Date().getTime();
    
    // Check if lastShown exists and if it was shown less than 5 minutes ago (300000 milliseconds)
    if (lastShown && (currentTime - lastShown < 300000)) {
        return false;
    }

    // Update last shown time
    localStorage.setItem('lastPopupTime', currentTime);
    return true;
}

window.onload = function() {
    // Show popup if allowed by the 5-minute rule
    if (shouldShowPopup()) {
        openPopup();
    }

    // Show popup every 5 minutes
    setInterval(() => {
        if (shouldShowPopup()) {
            openPopup();
        }
    }, 300000); // 5 minutes

    // Close popup on 'OK' button or 'X' close icon click
    document.getElementById('okButton').onclick = function() {
        document.getElementById('factPopup').style.display = 'none';
    };
    document.querySelector('.close').onclick = function() {
        document.getElementById('factPopup').style.display = 'none';
    };
};

      
      </script>
      


  </body>
</html>

website/templates/home.html
{% extends "base.html" %}
{% block title %}Home{% endblock %}

{% block content %}

<link
  rel="stylesheet"
  href="{{ url_for('static', filename='css/home.css') }}"
/>

<link
  rel="stylesheet"
  href="{{ url_for('static', filename='css/about.css') }}"
/>

<section class="hero">
  <div class="slider-container">
    <div class="slides">
      <!-- Hero Image as part of the slider -->
      <div class="hero">
        <div class="hero-image">
          
            
          
        </div>
      </div>
    </div>
  </div>
</section>

<section class="circles-section"> 
  <div class="hero-text">
  <h1>Welcome to Easy Link</h1>
  <p>Redefining Learning</p>
</div>
  <div class="circles-container">
    <div class="circle">
      <div class="circle-content front">EAT</div>
      <div class="circle-content back">Everyday</div>
    </div>
    <div class="circle">
      <div class="circle-content front">TALK</div>
      <div class="circle-content back">We Learn</div>
    </div>
    <div class="circle">
      <div class="circle-content front">LEARN</div>
      <div class="circle-content back">Something</div>
    </div>
    <div class="circle">
      <div class="circle-content front">APPLY</div>
      <div class="circle-content back">New!</div>
    </div>
  </div>
</section>

<section class="about">
  <div class="about-content">
    <h2>About Us</h2>
    <p> At Easy Link, we are dedicated to bridging the digital divide by providing offline access to educational content, specifically focusing on informal ICT education. Our mission is to empower communities in remote or underdeveloped areas by delivering essential learning resources without the need for an active internet connection. We achieve this through an innovative system built around Raspberry Pi, a microcontroller that acts as a local server, enabling offline access to e-books, courses, and educational materials.
      
     <p> Powered by a solar-charged power bank, our Raspberry Pi setup is particularly effective in regions with abundant sunlight, making it a sustainable and reliable solution for education in even the most isolated areas. We partner with organizations engaged with schools to deliver this system, ensuring wide distribution to learning institutions. </p>
      
     <p>  Our focus is on providing content that nurtures ICT skills, using free resources such as courses and textbooks from reputable organizations with a strong presence in the digital movement, like Microsoft. By offering this platform, we aim to equip learners with the digital skills necessary for the future, ensuring no one is left behind in the age of technology.</p>
      
     <p> At Easy Link, we believe in the transformative power of education and technology, and we're committed to empowering communities and fostering educational growth where it's needed most.</p>
    <p>Our commitment extends beyond mere innovation. We work tirelessly to integrate sustainability into every aspect of our operations, ensuring that every step we take brings us closer to a greener and more connected world. Join us on our journey as we turn ideas into action, and transform our vision of a sustainable future into reality.</p>
    <a href="{{ url_for('views.about') }}" class="learn-more-link">Learn More</a>
  </div>
</section>


<script>
  let currentSlide = 0;

  function moveSlide(step) {
    const slides = document.querySelector('.slides');
    const totalSlides = document.querySelectorAll('.slide').length;

    currentSlide = (currentSlide + step + totalSlides) % totalSlides;
    slides.style.transform = `translateX(-${currentSlide * 100}%)`;
  }

  // Optional: Automatically slide every 5 seconds
  setInterval(() => moveSlide(1), 5000);



</script>

<div id="chatbot-container" class="chatbot-container">
  <div class="chatbot-icon">
    <img src="/static/images/bot.jpg" alt="Chat Icon" />
  </div>
  <div id="chatbot-expanded" class="chatbot-expanded">
    <button class="close-chatbot">&times;</button> 
    <iframe 
    src="https://creator.voiceflow.com/prototype/66c5a888f9ca8d559e85ba72" 
    frameborder="0" 
    title="Voiceflow Prototype 66c5a888f9ca8d559e85ba72">
</iframe>

  </div>
</div>


<script>
  document.addEventListener('DOMContentLoaded', function() {
    var chatbotIcon = document.querySelector('.chatbot-icon');
    var chatbotExpanded = document.getElementById('chatbot-expanded');

    chatbotIcon.addEventListener('click', function() {
      // Toggle the display of the expanded view
      if (chatbotExpanded.style.display === 'block') {
        chatbotExpanded.style.display = 'none';
      } else {
        chatbotExpanded.style.display = 'block';
      }
    });

    // Optional: Add functionality to close the chatbot
    var closeChatbot = document.querySelector('.close-chatbot');
    if (closeChatbot) {
      closeChatbot.addEventListener('click', function() {
        chatbotExpanded.style.display = 'none';
      });
    }
  });
</script>



{% endblock %}

website/templates/ict.html
{% extends "base.html" %}
{% block title %}Cisco{% endblock %}

{% block content %}
<link
  rel="stylesheet"
  href="{{ url_for('static', filename='css/sectorA.css') }}"
/>

<div class="title-container">
  <h2 class="page-title">IoT</h2>
</div>

{% endblock %}

website/templates/login.html
{% extends "base.html" %}
{% block title %}Home{% endblock %}

{% block content %}

<link
  rel="stylesheet"
  href="{{ url_for('static', filename='css/login.css') }}"
/>

<form method="POST">
    <h3 align="center">Login</h3>
 
   
    <div class="form-group">
        <label for="email">Email Address</label>
        <input type="email" class="form-control" id="email" name="email" placeholder="Enter email";/>
    </div>

    <div class="form-group">
        <label for="password">Password</label>
        <input type="password" class="form-control" id="password" name="password" placeholder="Enter password";/>
    </div>

    <br/>
    <button type="submit" class="btn btn-primary">Login</button>



{% endblock %}

website/templates/math.html
{% extends "base.html" %}
{% block title %}Cisco{% endblock %}

{% block content %}
<link rel="stylesheet" href="{{ url_for('static', filename='css/sectorA.css') }}" />
    <link rel="stylesheet" href="{{ url_for('static', filename='css/math.css') }}" />
    <title>Micro-Controller</title>
    <style>
        .model-page {
            display: none; /* Hide all model pages initially */
        }
    </style>
</head>
<body>
    <div class="title-container">
        <h2 class="page-title">MATHEMATICS</h2>
    </div>
  </body>

    
{% endblock %}

website/templates/memo.html
{% extends "base.html" %}
{% block title %}Memo{% endblock %}

{% block content %}

<link rel="stylesheet" href="{{ url_for('static', filename='css/memo.css') }}" />

<div class="title-container">
    <h2 class="page-title">Memo</h2>
</div>

<div id="memo-posts">
    {% for post in posts %}
    <div class="memo-post">
        <a href="{{ post.pdf }}" download>
            <img src="{{ url_for('static', filename='uploads/' + post.image) }}" alt="Memo Image">
        </a>
    </div>
    {% endfor %}
</div>

{% endblock %}